const columnsRaw = `column 1 = 
Fedex/standard
Fedex/No Charge
Owaiz
Yes
NA
Count Number of LineID ..Just provide the Number

Column 2 =

1 REF  ATTACHED ART AND DUPLICATE
LC THERE WILL BE LEFT CHEST PRINT
FC THERE WILL BE FULL CHEST PRINT
FB THERE WILL BE FULL BACK PRINT
SUB THERE WILL BE SMALL UPPER BACK PRINT
SCC THERE WILL BE SMALL CENTER CHEST PRINT
FSR THERE WILL BE FULL SLEEVE RIGHT PRINT
FSL THERE WILL BE FULL SLEEVE LEFT PRINT
LBI THERE WILL BE LEFT BICEP PRINT
MB THERE WILL BE MIDDLE BACK PRINT
RBI THERE WILL BE RIGHT BICEP PRINT
LC THERE WILL BE LEFT CHEST PRINT
FUAL THERE WILL BE Full upper arm left sleeve - Max width of 7 inches starting from RBI / LBI down PRINT
1LS THERE WILL Left Sleeve (1 INCH ABOVE THE CUFF) PRINT


Column 3 =

PLEASE CREATE THE ART WITH BLANKET ONLY

PLEASE CREATE THE ART WITH BAG ONLY
`;

export default columnsRaw;

